TACO-325 Add AllowedPublisherLegitimateInterest to TCF string
Wikia/tracking-opt-in pull request #316
Opened 2024-01-08 15:20 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/TACO-325

### Description
In this PR I've added missing Publisher Legitimate Interests (2, 7 , 8, 9, 10, 11) to the TCF string composed by Tracking Opt In.

2024-01-08 16:56 UTC, bckatarzyna approved these changes

2024-01-09 08:00 UTC, bckatarzyna requested changes

2024-01-09 08:16 UTC, szymon-nawrocki commented on src/gdpr/ConsentManagementProvider.js
> +        tcModel.publisherLegitimateInterests.set(ALLOWED_PUBLISHER_LEGITIMATE_INTERESTS);
I thought that **purpose**LegitimateInterest and **publisher**LegitimateInterest are something different. At least they appear as a separate blocks in TCF string

2024-01-09 08:25 UTC, bckatarzyna approved these changes

2024-01-10 09:31 UTC, merged